### ISSUE TITLE
Rome, Naples and Florence are in Italy also!

### ISSUE THREAD

**Issue by Hermanallan** [roselloryan/WeatherApp#1]
Dear Sir,
How could you leave out some many beautiful cities from your app? Rome??? 
Is there an app for the transmission of tears?

**Comment by roselloryan** [comment]
@Hermanallan No tears! They're in there. Search for Roma, Napoli, and Firenze. :)

**Comment by Hermanallan** [comment]
Yes they are! What did you do?
Thank you!
Allan

**Comment by roselloryan** [comment]
I just search for them by their Italian names. Seems that is how they were stored in the OpenWeatherMaps API.
